---
title: Statistical analysis
---

::: {.callout-tip}
#### Learning Objectives

* Acknowledge the availability of different R/Bioconductor packages for carrying out differential expression (abundance) analyses
* Using the `Limma` package, design a statistical model to test for differentially abundant proteins between two conditions
* Be able to interpret the output of a statistical model and annotate the results with user-defined significance thresholds
* Produce volcano plots and MA plots to visualise the results of differential expression analyses
* Export key results from R using `write_csv` and figures using `ggsave`

:::


## Differential expression analysis 

Having cleaned our data, aggregated from PSM to protein level, completed a
log2 transformation and normalised the data, we are now ready to carry out
statistical analysis. The aim of this section is to answer the question:
*"Which proteins show a significant change in abundance between cell cycle stages?"*.

Our null hypothesis is:
**(H0)** The change in abundance for a protein between cell cycle stages is 0.

Our alternative hypothesis is:
**(H1)** The change in abundance for a protein between cell cycle stages is greater than 0.


### Selecting a statistical test

There are a few aspects of our data that we need to consider prior to deciding
which statistical test to apply.

* The protein abundances in this data are not normally distributed (i.e., they do not follow a Gaussian distribution). However, they are approximately normal following a log2 transformation.
* The cell cycle is **not** expected to have a large impact on biological variability. We can assume that the majority of the proteome is the same between samples.
* The samples are independent not paired. For example, M_1 is not derived from the same cells as G1_1 and DS_1.

The first two points relate to two key assumptions that are made when carrying out 
**parametric** statistical tests. Parametric tests provide greater statistical 
power but assume that the input data has a normal distribution and equal variance.
If these two assumptions are not met then it is not appropriate to use parametric 
testing. If we wanted to check whether the log2 protein abundances were truly 
Gaussian we could have applied a Shapiro-Wilk test or Kolmogorov-Smirnov test.
Similarly, to check for equal variance a Levene test could be used. All of these
tests are easily done within R but will not be covered in this course. Here, we
will use a form of t-test since we know that these assumptions have been met.


### Using the empirical Bayes moderated t-test from the `Limma` package

* Explain each term - Bayes moderated, t-test
* Explain the concept of contrasts
* Discuss the two types of limma model (trend = TRUE)


### Diagnostic plots to verify suitability of our statistical model

* p-value histogram 
* SA plot

### Interpreting the output of our statisical model

#### Adding user-defined significance thresholds based on FDR and LFC

* Discussion about p-value correction and why it is needed -> FDR as a method for this
* Discussion about whether a log2FC threshold should also be set -> mention MS2 TMT ratio compression



### Visualising the results of our statistical model

* Volcano plot
* MA plot
* Adding error bars to show confidence interval 

::: {.callout-tip}
#### Key Points

- Last section of the page is a bulleted summary of the key points
:::
